################
# DrupalCI GitLabCI template
#
# Gitlab-ci.yml to replicate DrupalCI testing for Contrib
#
# With thanks to:
#   * The GitLab Acceleration Initiative participants
#   * DrupalSpoons
################

################
# Guidelines
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification. It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
#
# However, you can modify this template if you have additional needs for your project.
################

################
# Includes
#
# Additional configuration can be provided through includes.
# One advantage of include files is that if they are updated upstream, the changes affect all pipelines using that include.
#
# Includes can be overridden by re-declaring anything provided in an include, here in gitlab-ci.yml
# https://docs.gitlab.com/ee/ci/yaml/includes.html#override-included-configuration-values
################

include:
  ################
  # DrupalCI includes:
  # As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
  # View these include files at https://git.drupalcode.org/project/gitlab_templates/
  ################
  - project: $_GITLAB_TEMPLATES_REPO
    # "ref" value can be:
    # - Recommended (default) - `ref: $_GITLAB_TEMPLATES_REF` - The Drupal Association will update this value to the recommended tag for contrib.
    # - Latest - `ref: main` - Get the latest additions and bug fixes as they are merged into the templates.
    # - Minor or Major latests - `ref: 1.x-latest` or `ref: 1.0.x-latest` - Get the latest additions within a minor (mostly bugfixes) or major (bugs and new features).
    # - Fixed tag - `ref: 1.0.1` - Set the value to a known tag. This will not get any updates.
    # If you change the default value of ref, you should set the _CURL_TEMPLATES_REF variable in the variables section to be the same as set here.
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - "/includes/include.drupalci.main.yml"
      # For Drupal 7, remove the above line and uncomment the below.
      # - "/includes/include.drupalci.main-d7.yml"
      - "/includes/include.drupalci.variables.yml"
      - "/includes/include.drupalci.workflows.yml"

stages:
  - development
  - build
  - validate
  - test
  - publish

#
################
# Pipeline configuration variables
#
# These are the variables provided to the Run Pipeline form that a user may want to override.
#
# Docs at https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
################
variables:
  # Experience Builder aims to match Drupal 11's minimum PHP and MySQL versions even in its Drupal 10 support.
  CORE_PHP_MIN: '8.3'
  # Opt in to testing $CORE_MAJOR_DEVELOPMENT (currently Drupal 11).
  OPT_IN_TEST_NEXT_MAJOR: '1'

  # Show env variables always while Drupal 11 is in flux and GitLab CI templates are flaky too.
  _SHOW_ENVIRONMENT_VARIABLES: 1

# This module wants to strictly comply with Drupal core's word use standards.
cspell:
  # Match Drupal 11's rules, not 10.3's.
  needs:
    - "composer (next major)"
  allow_failure: false

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.is-push-rule: &is-push-rule
  if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"

.manual-rule: &manual-rule
  - when: manual
    allow_failure: true

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.php-files-change-rule: &php-files-change-rule
  - changes:
      - "**/*.{php,module,inc,install,theme,profile}"
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.css-files-change-rule: &css-files-change-rule
  - changes:
      - "**/*.css"
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.module-metadata-files-change-rule: &module-metadata-files-change-rule
  - changes:
      - "*.yml"
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.module-config-files-change-rule: &module-config-files-change-rule
  - changes:
      # config schema and/or default config
      - config
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
.SDC-files-change-rule: &SDC-files-change-rule
  - changes:
      - components
      - schema.json
    when: on_success

# @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
composer-lint:
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - changes:
        - composer.json
      when: on_success
    - *manual-rule

phpcs:
  needs:
    - "composer (next major)"
  allow_failure: false
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    # Also run whenever we catch up to the upstream PHPCS rules.
    - changes:
        - core.phpcs.xml.dist
      when: on_success
    - *manual-rule

phpcs-rules-match-drupal-11:
  stage: development
  script:
    - |
      # Download the file from the Drupal repository
      curl -o drupal_core_phpcs.xml.dist https://git.drupalcode.org/project/drupal/-/raw/11.x/core/phpcs.xml.dist?ref_type=heads

      # Check if the download was successful
      if [ $? -ne 0 ]; then
        echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
        echo "Error: Failed to download $DRUPAL_URL"
        exit 1
      fi

      # Compare the downloaded file with the local file using a subshell to prevent premature exit
      echo "Comparing downloaded file with local file..."
      # With uses the braces the job just ends here for some reason.
       {
        diff drupal_core_phpcs.xml.dist core.phpcs.xml.dist
        DIFF_EXIT_CODE=$?
      } || true

      if [ $DIFF_EXIT_CODE -ne 0 ]; then
        echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
        echo "Error: core.phpcs.xml.dist not up to date with Drupal 11.x core/phpcs.xml.dist. Please create an issue to update this file."
      else
        echo "👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍"
        echo "core.phpcs.xml.dist is up to date with Drupal 11.x core/phpcs.xml.dist"
      fi

      # Exit with the exit code of the diff command
      exit $DIFF_EXIT_CODE
  # Allow this to fail, to avoid disrupting XB's CI when upstream changes.
  allow_failure: true
stylelint:
  # Match Drupal 11's rules, not 10.3's.
  needs:
    - "composer (next major)"
  allow_failure: false
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *css-files-change-rule
    - *manual-rule

# This module wants to strictly comply with PHPStan.
.phpstan-base:
  allow_failure: false
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - *manual-rule
# Sadly, changes to `.phpstan-base` do not affect derivatives that themselves override `rules`… 😬
phpstan (next major):
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - *manual-rule

# We're choosing to not use `OPT_IN_TEST_NEXT_MINOR` but instead force the default CI build job to use Drupal 10.3.
composer:
  variables:
    # Test not against the current minor, but the next minor.
    DRUPAL_CORE: $CORE_NEXT_MINOR
    IGNORE_PROJECT_DRUPAL_CORE_VERSION: 1

phpunit:
  parallel:
    # @see https://www.drupal.org/node/3444548
    matrix:
      - _TARGET_DB_TYPE: sqlite
        _TARGET_DB_VERSION: '3'
        # @see https://git.drupalcode.org/project/drupal/-/commit/10466dba9d7322ed55165dd9224edb2153c9b27a
        _TARGET_PHP: '8.3-ubuntu'
      - _TARGET_DB_TYPE: 'mariadb'
        _TARGET_DB_VERSION: '10.6'
      - _TARGET_DB_TYPE: 'mysql'
        # @todo Delete this when https://www.drupal.org/project/gitlab_templates/issues/3447105 lands.
        _TARGET_DB_VERSION: '8'
      - _TARGET_DB_TYPE: 'pgsql'
        _TARGET_DB_VERSION: '16'
  # @todo Delete this after https://www.drupal.org/project/gitlab_templates/issues/3447792 lands.
  # @see https://git.drupalcode.org/issue/gitlab_templates-3447792/-/compare/main...3447792-raise-sqlite-version?from_project_id=96292, when 984abb7b4781559a13078d58bb65f6959fe42179 was the last commit.
  image:
    name: $_CONFIG_DOCKERHUB_ROOT/php-$PHP_VERSION-ubuntu-apache:$_TARGET_PHP_IMAGE_TAG
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - *module-metadata-files-change-rule
    - *module-config-files-change-rule
    - *SDC-files-change-rule
    - *manual-rule
# Sadly, changes to `phpunit` do not affect derivatives that themselves override `rules`… 😬
phpunit (next major):
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - *php-files-change-rule
    - *module-metadata-files-change-rule
    - *module-config-files-change-rule
    - *SDC-files-change-rule
    - *manual-rule

eslint:
  # This module wants to strictly comply with eslint.
  allow_failure: false
  before_script:
    # 🤷‍.eslintignore already instructs eslint to ignore this, but it does not seem to work. This is validated by the `UI - eslint` job below.
    - rm -rf ui
  # @todo Remove when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - .prettier*
        - "**/*.js"
        - "**/*.yml"
    - *manual-rule

UI:
  stage: build
  image: node:20-alpine
  needs: []
  script:
    - cd ui
    - npm ci
    # Verify building the entire app succeeds — this first runs the TypeScript Compiler.
    - npm run build
    # @todo In the future, when `ui/dist` is committed, verify here that it matches.
  artifacts:
    paths:
      - ui/dist
      # TRICKY: necessary for the `Cypress` job to be able to run `cypress install`.
      - ui/node_modules

UI eslint:
  stage: validate
  image: node:20-alpine
  allow_failure: false
  needs:
    - UI
  # @todo Refine when https://www.drupal.org/project/gitlab_templates/issues/3452183 lands.
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/package.json
        - ui/**/*.ts
        - ui/**/*.tsx
        - ui/tsconfig.json
        - ui/tsconfig.node.json
    - *manual-rule
  script:
    - cd ui
    - npm ci
    # First, generate the `junit.xml` for code quality. Violations will not cause this to fail.
    - node_modules/.bin/eslint . --format=junit --output-file=$CI_PROJECT_DIR/junit.xml
    # Second, explicitly pass/fail this job.
    - npm run lint
  artifacts:
    expose_as: junit
    expire_in: 6 mos
    when: always
    name: artifacts-$CI_PIPELINE_ID-$CI_JOB_NAME_SLUG
    paths:
      - junit.xml
    reports:
      junit: junit.xml

.cypress-base:
  stage: test
  needs:
    - composer
    - UI
  extends:
    - .test-variables
  before_script:
    - echo -e "\e[0Ksection_start:`date +%s`:Cypress-deps[collapsed=true]\r\e[0KInstall Cypress dependencies."
    - sudo apt-get -y update
    - sudo apt-get -y install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
    - echo -e "\e[0Ksection_end:`date +%s`:Cypress-deps\r\e[0K"
    #
    # Copied from `.nightwatch-base`, but converted to use GitLab CI references.
    # 👇
    #
    - !reference [ .setup-webserver ]
    - !reference [ .simpletest-db ]
    - export DRUPAL_TEST_DB_URL=$SIMPLETEST_DB
    - !reference [ .show-environment-variables ]
    - cd $_WEB_ROOT
    #
    # 👆
    #
    - cd modules/custom/$CI_PROJECT_NAME
    - echo -e "\e[0Ksection_start:`date +%s`:Cypress-install[collapsed=true]\r\e[0KInstall Cypress."
    - cp ./ui/.env.example ./ui/.env
    - echo "BASE_URL='${SIMPLETEST_BASE_URL}'" >> ./ui/.env
    - echo "DB_URL='${DRUPAL_TEST_DB_URL}'" >> ./ui/.env
    - echo "DRUPAL_TEST_WEBSERVER_USER=www-data" >> ./ui/.env
    - echo "DRUPAL_ROOT_CORE='${CI_PROJECT_DIR}/${_WEB_ROOT}/core'" >> ./ui/.env
    - cd ./ui/
    - cat .env
    - mkdir -p ./cycache /var/www/.npm /home/apache/.cache/fontconfig ~/.cache /usr/share/fonts/ /var/cache/fontconfig
    - chown -R www-data:www-data ./cycache /var/www/.npm /usr/bin/npm /home/apache/.cache/fontconfig ~/.cache /usr/share/fonts/ /var/cache/fontconfig
    - chmod -R 755 ./cycache
    - sudo -u www-data CYPRESS_CACHE_FOLDER=./cycache node ./node_modules/.bin/cypress install
    - echo -e "\e[0Ksection_end:`date +%s`:Cypress-install\r\e[0K"
    - sudo -u www-data CYPRESS_CACHE_FOLDER=./cycache node ./node_modules/.bin/cypress --version
  variables:
    _TARGET_DB_TYPE: sqlite
  artifacts:
    when: always
    expire_in: 6 mos
    paths:
      - ./tests/src/Cypress/cypress/screenshots/**/*.png

cypress E2E:
  extends: .cypress-base
  script:
    - CYPRESS_CACHE_FOLDER=./cycache node ./node_modules/.bin/cypress run --browser electron

cypress unit:
  extends: .cypress-base
  script:
    - CYPRESS_CACHE_FOLDER=./cycache node ./node_modules/.bin/cypress run --component --browser electron
  rules:
    - *is-push-rule
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - ui/src/**/*
        - ui/tsconfig.json
        - ui/tsconfig.node.json
        - tests/src/Cypress/cypress/unit/**/*
    - *manual-rule

🗺️ C4 model diagrams:
  stage: validate
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docs/XB.dsl
        - docs/diagrams/*
  image:
    name: structurizr/cli
    entrypoint: [""]
  script:
    - /usr/local/structurizr-cli/structurizr.sh export --workspace docs/XB.dsl --format mermaid --output $CI_PROJECT_DIR/docs/diagrams
    # Prepend the prefix
    #   ```mermaid
    # and the
    #   ```
    # suffix that GitLab CI expects.
    # @see https://docs.gitlab.com/ee/user/markdown.html#mermaid
    # @see https://stackoverflow.com/a/42989868
    # @see https://stackoverflow.com/a/9741470
    - for file in docs/diagrams/*.mmd; do printf "\`\`\`mermaid\n" | cat - $file  > temp && mv -f temp $file && echo $'\n```' >> $file; done
    # Now the actual validation: verify that regenerating the Mermaid Markdown files did NOT trigger any changes.
    - set -e; for file in docs/diagrams/*.mmd; do diff $file docs/diagrams/$(basename $file mmd)md; done
  artifacts:
    paths:
      - "docs/diagrams/*.md"
