<?php

/**
 * @file
 * Hook implementations for Experience Builder's foundational functionality.
 *
 * Other hook implementations live in include files.
 */

// @todo Re-evaluate this when A) tagging a stable release, B) https://www.drupal.org/project/drupal/issues/3398033 is fixed in Drupal core.
ini_set('assert.active', 1);

use Drupal\Core\Render\Markup;

// Hook implementations for specific areas:
// @see docs/components.md, section 3.3.3
require_once __DIR__ . '/experience_builder.block_overrides.inc';

/**
 * Implements hook_preprocess_HOOK() for regions.
 *
 * @see \Drupal\experience_builder\Render\MainContent\XBPreviewRenderer::prepare()
 */
function experience_builder_preprocess_region(array &$variables):void {
  if (!array_key_exists('#xb_region_preview', $variables['elements'])) {
    // Nothing to do: this is a region being rendered outside of an XB preview
    // context.
    return;
  }

  $region = $variables['region'];
  assert(is_string($region) && strlen($region) >= 1);

  $content = (string) $variables['content'];

  // Additional `content-start` and `content-end` comment annotations to surround just the {{ content }} output
  // to allow XB's UI to more accurately render the region overlays
  $variables['content'] = Markup::create(<<<HTML
<!-- xb-region-content-start-$region -->
$content
<!-- xb-region-content-end-$region -->
HTML);
}

/**
 * Implements hook_module_implements_alter().
 *
 * @todo Refactor this once XB requires Drupal 11.2, to use https://www.drupal.org/node/3497308.
 */
function experience_builder_module_implements_alter(array &$implementations, mixed $hook): void {
  // Make the form alter hooks in this module run last.
  if ($hook === 'form_alter') {
    $group = $implementations['experience_builder'];
    unset($implementations['experience_builder']);
    $implementations['experience_builder'] = $group;
  }
}

/**
 * Implements hook_preprocess_form_element().
 */
function experience_builder_preprocess_form_element(array &$variables): void {
  if (!isset($variables['label'])) {
    return;
  }

  if (isset($variables['element']['#form_id'])) {
    $variables['label']['#form_id'] = $variables['element']['#form_id'];
  }
}

/**
 * Implements hook_preprocess_HOOK() for html.
 */
function experience_builder_preprocess_html(array &$variables): void {
  $current_route = \Drupal::routeMatch()->getRouteName();
  if ($current_route === 'entity.xb_page.canonical') {
    $variables['attributes']['class'][] = 'xb-page';
  }
}
