<?php

declare(strict_types=1);

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_install().
 */
function experience_builder_install(): void {
  // Automatically set up the Standard install profile's "article" content type
  // to demo/test Experience Builder.
  if (!\Drupal::moduleHandler()->moduleExists('node')) {
    return;
  }
  if (NodeType::load('article')) {
    \Drupal::service('entity_display.repository')
      ->getFormDisplay('node', 'article')
      ->setComponent('field_hero', [
        'type' => 'image_image',
        'weight' => 1,
      ])
      ->save();
    \Drupal::service('entity_display.repository')
      ->getViewDisplay('node', 'article')
      ->setComponent('field_xb_demo', [
        'type' => 'experience_builder_naive_render_sdc_tree',
        // The image field has weight -1 by default.
        'weight' => -2,
      ])
      ->save();
  }

  // Cache flush ensures the contextual form works.
  drupal_flush_all_caches();
}

/**
 * Implements hook_module_preinstall().
 */
function experience_builder_module_preinstall(string $module): void {
  if ($module !== 'experience_builder') {
    return;
  }

  // Register the JSON schema definitions stream wrapper *prior* to installing
  // default config and hence prior to config validation. Otherwise validation
  // fails.
  // @see \Drupal\experience_builder\JsonSchemaDefinitionsStreamwrapper
  // @see \Drupal\Core\Extension\ModuleInstaller::install()
  // @todo Remove this after https://www.drupal.org/project/drupal/issues/3352063 lands.
  \Drupal::service('stream_wrapper_manager')->register();
}
