<?php

/**
 * @file
 * Hook implementations for Experience Builder's foundational functionality.
 *
 * Other hook implementations live in include files.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Block\BlockManagerInterface;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Entity\TypedData\EntityDataDefinition;
use Drupal\Core\EventSubscriber\AjaxResponseSubscriber;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItem;
use Drupal\experience_builder\Entity\Component;
use Drupal\experience_builder\Form\FormIdPreRender;
use Drupal\experience_builder\Entity\PageTemplate;
use Drupal\experience_builder\Plugin\ComponentPluginManager;
use Drupal\Core\Validation\Plugin\Validation\Constraint\FullyValidatableConstraint;
use Drupal\experience_builder\Plugin\ExperienceBuilder\ComponentSource\BlockComponent;
use Drupal\experience_builder\PropExpressions\StructuredData\FieldPropExpression;
use Drupal\experience_builder\PropExpressions\StructuredData\FieldTypeObjectPropsExpression;
use Drupal\experience_builder\PropExpressions\StructuredData\FieldTypePropExpression;
use Drupal\experience_builder\PropExpressions\StructuredData\ReferenceFieldPropExpression;
use Drupal\experience_builder\PropExpressions\StructuredData\ReferenceFieldTypePropExpression;
use Drupal\experience_builder\PropShape\CandidateStorablePropShape;
use Drupal\media\Entity\MediaType;

// Hook implementations for specific areas:
// @see docs/redux-integrated-field-widgets.md
require_once __DIR__ . '/experience_builder.redux_integrated_field_widgets.inc';
// @see docs/semi-coupled-theme-engine.md
require_once __DIR__ . '/experience_builder.semi_coupled_theme_engine.inc';
// @see docs/data-model.md, section 3.1.2
require_once __DIR__ . '/experience_builder.shape_matching.inc';

require_once __DIR__ . '/experience_builder.force_render_with_twig.inc';

/**
 * Implements hook_form_alter().
 */
function experience_builder_form_alter(array &$form, FormStateInterface $form_state, string $form_id): void {
  experience_builder_force_render_with_twig_form_alter($form, $form_state, $form_id);

  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name === 'experience_builder.api.entity_form') {
    // Hide submit buttons on the entity form accessed via the XB app.
    $form['actions']['#access'] = FALSE;
    // Add form ID to elements.
    $form['#pre_render'][] = [FormIdPreRender::class, 'addFormId'];
    $form['#attributes']['data-form-id'] = 'page_data_form';
    if (\Drupal::request()->get(AjaxResponseSubscriber::AJAX_REQUEST_PARAMETER) !== NULL) {
      // Add the data-ajax flag and manually add the form ID as pre render
      // callbacks aren't fired during AJAX rendering because the whole form is
      // not rendered, just the returned elements.
      FormIdPreRender::addAjaxAttribute($form, 'page_data_form');
    }
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function experience_builder_module_implements_alter(array &$implementations, string $hook): void {
  // Make the form alter hooks in this module run last.
  if ($hook === 'form_alter') {
    $group = $implementations['experience_builder'];
    unset($implementations['experience_builder']);
    $implementations['experience_builder'] = $group;
  }
}

/**
 * Implements hook_storage_prop_shape_alter().
 *
 * (On behalf of the Media Library module.)
 *
 * Overrides the default: the "image" field type + widget.
 *
 * @see \Drupal\experience_builder\JsonSchemaInterpreter\SdcPropJsonSchemaType::computeStorablePropShape()
 * @todo Move to Media Library module, eventually.
 */
function media_library_storage_prop_shape_alter(CandidateStorablePropShape $storable_prop_shape): void {
  if ($storable_prop_shape->shape->schema == ['type' => 'object', '$ref' => 'json-schema-definitions://experience_builder.module/image']) {
    // @todo Allow configuring which media type, for now this assumes the
    //   Standard 'image' media type.
    // @see core/profiles/standard/config/optional/media.type.image.yml
    if (!MediaType::load('image')) {
      return;
    }

    $storable_prop_shape->fieldTypeProp = new FieldTypeObjectPropsExpression('entity_reference', [
      'src' => new ReferenceFieldTypePropExpression(
        new FieldTypePropExpression('entity_reference', 'entity'),
        new ReferenceFieldPropExpression(
          new FieldPropExpression(EntityDataDefinition::create('media', 'image'), 'field_media_image', NULL, 'entity'),
          new FieldPropExpression(EntityDataDefinition::create('file'), 'uri', NULL, 'url'),
        )
      ),
      'alt' => new ReferenceFieldTypePropExpression(
        new FieldTypePropExpression('entity_reference', 'entity'),
        new FieldPropExpression(EntityDataDefinition::create('media', 'image'), 'field_media_image', NULL, 'alt'),
      ),
      'width' => new ReferenceFieldTypePropExpression(
        new FieldTypePropExpression('entity_reference', 'entity'),
        new FieldPropExpression(EntityDataDefinition::create('media', 'image'), 'field_media_image', NULL, 'width'),
      ),
      'height' => new ReferenceFieldTypePropExpression(
        new FieldTypePropExpression('entity_reference', 'entity'),
        new FieldPropExpression(EntityDataDefinition::create('media', 'image'), 'field_media_image', NULL, 'height'),
      ),
    ]);
    $storable_prop_shape->fieldStorageSettings = [
      'target_type' => 'media',
    ];
    $storable_prop_shape->fieldInstanceSettings = [
      'handler' => 'default:media',
      'handler_settings' => [
        'target_bundles' => [
          'image' => 'image',
        ],
      ],
    ];
    $storable_prop_shape->fieldWidget = 'media_library_widget';
  }
}

/**
 * Implements hook_storage_prop_shape_alter().
 *
 * (On behalf of the Date Range module.)
 *
 * @see \Drupal\experience_builder\JsonSchemaInterpreter\SdcPropJsonSchemaType::computeStorablePropShape()
 * @see \Drupal\datetime_range\Plugin\Field\FieldType\DateRangeItem
 */
function datetime_range_storage_prop_shape_alter(CandidateStorablePropShape $storable_prop_shape): void {
  if ($storable_prop_shape->shape->schema == ['type' => 'object', '$ref' => 'json-schema-definitions://sdc_test_all_props.module/date-range']) {
    $storable_prop_shape->fieldTypeProp = new FieldTypeObjectPropsExpression(
      'daterange',
      [
        'from' => new FieldTypePropExpression('daterange', 'end_value'),
        'to' => new FieldTypePropExpression('daterange', 'value'),
      ]
    );
    $storable_prop_shape->fieldStorageSettings = ['datetime_type' => DateTimeItem::DATETIME_TYPE_DATE];
    $storable_prop_shape->fieldWidget = 'daterange_default';
  }
}

/**
 * Implements hook_modules_installed().
 */
function experience_builder_modules_installed(array $modules, bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }
  // The module installer cleared all plugin caches. Create/update Component
  // config entities for all XB Component source plugins.
  // @see \Drupal\experience_builder\Plugin\ExperienceBuilder\ComponentSource\BlockComponent
  \Drupal::service(BlockManagerInterface::class)->getDefinitions();
  // @see \Drupal\experience_builder\Plugin\ExperienceBuilder\ComponentSource\SingleDirectoryComponent
  \Drupal::service(ComponentPluginManager::class)->getDefinitions();
}

/**
 * Implements hook_rebuild().
 */
function experience_builder_rebuild(): void {
  // The module installer cleared all plugin caches. Create/update Component
  // config entities for all XB Component source plugins.
  // @see \Drupal\experience_builder\Plugin\ExperienceBuilder\ComponentSource\BlockComponent
  \Drupal::service(BlockManagerInterface::class)->getDefinitions();
  // @see \Drupal\experience_builder\Plugin\ExperienceBuilder\ComponentSource\SingleDirectoryComponent
  \Drupal::service(ComponentPluginManager::class)->getDefinitions();
}

/**
 * Implements hook_block_alter().
 */
function experience_builder_block_alter(array &$definitions): void {
  static $in_recursion = FALSE;
  // Ensure we're not in infinite recursion.
  if ($in_recursion) {
    return;
  }

  // @todo Remove when minimum version is Drupal 11.1 following https://www.drupal.org/project/drupal/issues/3379725
  $additional = version_compare(\Drupal::VERSION, '11.1', '>=') ? [] : [
    'info' => '',
    'status' => TRUE,
    'view_mode' => '',
    'context_mapping' => [],
  ];

  // @todo This only handles new & existing Component entities in best case scenario, but does not handle cases where BlockComponent based entities exist, but Block Plugin definition is missing, see https://www.drupal.org/project/experience_builder/issues/3484682
  foreach ($definitions as $id => $definition) {
    if ($id === 'broken') {
      continue;
    }

    $component_id = 'block.' . str_replace(':', '.', $id);
    $component = Component::load($component_id);
    if ($component instanceof Component) {
      // @todo Update Component entities with BlockComponent source plugin: https://www.drupal.org/project/experience_builder/issues/3484682
      continue;
    }
    else {
      $in_recursion = TRUE;
      // @todo This is super ugly, decorate the block plugin manager so we can create instances directly?
      // @todo is this a not going to become performance bottle neck on BlockPlugin heavy sites?
      $block = \Drupal::service('plugin.manager.block')->createInstance($id);
      assert($block instanceof BlockPluginInterface);
      $settings = $block->defaultConfiguration();
      $data_definition = \Drupal::service('config.typed')->createFromNameAndData('block.settings.' . $id, $settings);
      // We currently support only block plugins with no settings, or if they do
      // have settings, they must be fully validatable.
      $fullyValidatable = FALSE;
      foreach ($data_definition->getConstraints() as $constraint) {
        if ($constraint instanceof FullyValidatableConstraint) {
          $fullyValidatable = TRUE;
          break;
        }
      }
      // @todo Remove the PageTitleBlock and SystemMessagesBlock special cases: make it fully validatable upstream in Drupal core. They are exempted here because of its crucial role in \Drupal\experience_builder\Entity\PageTemplate. Alternatively, this can be removed once XB requires Drupal 11.
      // @todo Remove the LocalActionsBlock special case: it is necessary to be able to test BlockPluginInterface::access() support *and* it has the exact same trivial settings as the two crucial blocks above. Alternatively, this can be removed once XB requires Drupal 11.
      if (!empty($settings) && !$fullyValidatable && $id !== 'page_title_block' && $id !== 'system_messages_block' && $id != 'local_actions_block') {
        continue;
      }
      $component = Component::create([
        'id' => $component_id,
        'label' => (string) $definition['admin_label'],
        'category' => (string) $definition['category'],
        'source' => BlockComponent::SOURCE_PLUGIN_ID,
        'settings' => [
          'plugin_id' => $id,
          // We are using strict config schema validation, so we need to provide valid settings for each block.
          'settings' => [
              // @todo if we need ID here can we merge settings with the parent and drop plugin_id?
            'id' => $id,
            'label' => (string) $definition['admin_label'],
            'label_display' => FALSE,
            'provider' => $definition['provider'],
          ] + $additional + $settings,
        ],
        'status' => TRUE,
      ]);
      $component->save();
      $in_recursion = FALSE;
    }
  }
}

/**
 * Implements hook_config_schema_info_alter().
 */
function experience_builder_config_schema_info_alter(array &$definitions): void {
  // This allows these blocks to be placed for now, but really the schema
  // should actually be FullyValidatable.
  // @todo Fix this in core or solve this another way in https://www.drupal.org/project/experience_builder/issues/3484666
  $types = ['block.settings.system_menu_block:*', 'block.settings.views_block:*'];
  foreach ($types as $type) {
    if (isset($definitions[$type])) {
      $definitions[$type]['constraints']['FullyValidatable'] = NULL;
    }
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function experience_builder_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];
  if ($entity_type->id() === 'xb_page') {
    // Modules providing an entity type cannot add dynamic base fields based on
    // other modules. The entity field manager determines if a field should be
    // installed based on its "provider", which is the module providing the
    // field definition. All fields from an entity's `baseFieldDefinitions` are
    // always set to the provider of the entity type.
    //
    // To work around this limitation, we provide the base field definition in
    // this hook, where we can specify the provider as the Metatag module.
    //
    // @see \Drupal\Core\Entity\EntityFieldManager::buildBaseFieldDefinitions()
    // @see \Drupal\Core\Extension\ModuleInstaller::install()
    if (\Drupal::moduleHandler()->moduleExists('metatag')) {
      $fields['metatags'] = BaseFieldDefinition::create('metatag')
        ->setLabel(t('Metatags'))
        ->setDescription(t('The meta tags for the entity.'))
        ->setTranslatable(TRUE)
        ->setDisplayOptions('form', [
          'type' => 'metatag_firehose',
          'settings' => [
            'sidebar' => TRUE,
            'use_details' => TRUE,
          ],
        ])
        ->setDisplayConfigurable('form', TRUE)
        // Instead of providing a `metatag_defaults` configuration entity, we
        // provide a default value for the field so that we do not have to
        // maintain (nor update) extra configuration.
        ->setDefaultValue(Json::encode([
          'title' => '[xb_page:title] | [site:name]',
          'description' => '[xb_page:description]',
          'canonical_url' => '[xb_page:url]',
          // @see https://stackoverflow.com/a/19274942
          'image_src' => '[xb_page:image:entity:field_media_image:entity:url]',
        ]))
        // Mark the field as internal. The Metatag module provides a computed
        // `metatag` field that is computed to combine the metatag defaults
        // with the entity's metatag overrides. By marking it internal, modules
        // like JSON:API can exclude the field from output when the entity is
        // normalized through the Serialization module.
        //
        // @see metatag_entity_base_field_info()
        ->setInternal(TRUE)
        // Set the provider as `metatag` so that Drupal installs the base field
        // when the Metatag module is installed.
        ->setProvider('metatag');
    }

  }
  return $fields;
}

/**
 * Implements hook_form_FORM_ID_alter() for system_theme_settings.
 */
function experience_builder_form_system_theme_settings_alter(array &$form, FormStateInterface $form_state): void {
  if (empty($form_state->getBuildInfo()['args'][0])) {
    // Do not alter the "Global settings" tab.
    return;
  }

  $theme = $form_state->getBuildInfo()['args'][0];
  $page_template = PageTemplate::load($theme);
  $enabled = $page_template && $page_template->status();

  $form['experience_builder'] = [
    '#type' => 'details',
    '#title' => t('Experience Builder'),
    '#weight' => -1,
    '#open' => TRUE,
  ];
  $form['experience_builder']['use_xb'] = [
    '#type' => 'checkbox',
    '#title' => t('Use Experience Builder for page templates in this theme.'),
    '#default_value' => $enabled,
  ];
  $regions = system_region_list($theme);
  $form['experience_builder']['editable'] = [
    '#type' => 'checkboxes',
    '#title' => t('Exposed regions'),
    '#options' => $regions,
    '#states' => [
      'visible' => [
        ':input[name="use_xb"]' => ['checked' => TRUE],
      ],
    ],
    '#default_value' => $page_template
      ? $page_template->getEditableRegions()
      : array_keys($regions),
  ];
  // The `content` region is a special case:
  // - it's the only region guaranteed to exist in every theme
  // - Experience Builder's UI does not allow adding component instances to it;
  //   it is always treated as only containing the main content block.
  // @see \Drupal\Core\Block\MainContentBlockPluginInterface
  $form['experience_builder']['editable']['content'] = ['#disabled' => TRUE];
  $form['experience_builder']['editable']['#description'] = t('Checked regions can be modified via Experience Builder. The <q>Content</q> region contains "the main content" on any route and cannot be modified further.');

  array_unshift($form['#submit'], 'experience_builder_form_system_theme_settings_submit');
}

function experience_builder_form_system_theme_settings_submit(array &$form, FormStateInterface $form_state): void {
  $theme = $form_state->getBuildInfo()['args'][0];
  $page_template = PageTemplate::load($theme);
  $enable = $form_state->getValue('use_xb');
  $editable = $form_state->getValue('editable');

  if ($enable) {
    $page_template ??= PageTemplate::createFromBlockLayout($theme);
    $page_template->enable()
      ->set('editable',
        // Checked checkboxes (even if disabled) get their (string) names.
        array_fill_keys(array_keys(array_filter($editable)), TRUE) +
        // Unchecked checkboxes get an integer zero.
        array_fill_keys(array_keys(array_filter($editable, fn ($v) => $v === 0)), FALSE)
      )
      ->save();
  }
  elseif ($page_template) {
    $page_template->disable()->save();
  }

  // Avoid polluting the theme settings config entity.
  $form_state->unsetValue('use_xb');
  $form_state->unsetValue('editable');
}
