<?php

/**
 * @file
 * Functions to support theming in the XB Stark theme.
 */

use Drupal\Component\Utility\NestedArray;
use Drupal\Core\Form\FormStateInterface;
use Drupal\xb_stark\PreRender;

function xb_stark_element_info_alter(array &$type): void {
  if (isset($type['vertical_tabs'])) {
    $type['vertical_tabs']['#pre_render'][] = [PreRender::class, 'verticalTabs'];
  }
  if (isset($type['table'])) {
    $type['table']['#pre_render'][] = [PreRender::class, 'table'];
  }
}

function xb_stark_form_node_form_alter(array &$form, FormStateInterface $form_state): void {
  // Inspired by Claro to render the sidebar details as accordions.
  $form['#theme'] = ['node_edit_form'];
  $form['advanced']['#accordion'] = TRUE;
  $form['meta']['#type'] = 'container';
  $form['meta']['#access'] = TRUE;
  $form['revision_information']['#type'] = 'container';
  $form['revision_information']['#group'] = 'meta';
}

function xb_stark_preprocess_field_multiple_value_form(array &$variables): void {
  $variables['attributes']['data-xb-multiple-values'] = 'true';
  // The default tabledrag group/target is the {table_id}-order but Radix
  // assigns this class to the trigger which is a button element. As a result
  // tabledrag.js does not set the value on the select after a drag/drop event
  // this causes the new order to be lost when the form is submitted. So we
  // change the group (which is used as a selector to target the weight field)
  // to select the adjacent select element.
  // @see tabledrag.js
  if (NestedArray::getValue($variables, ['table', '#tabledrag', 0, 'group'])) {
    $variables['table']['#tabledrag'][0]['group'] .= ' + select';
  }
}

/**
 * Implements hook_preprocess_hook().
 */
function xb_stark_preprocess_radios(array &$vars): void {
  // In inputBehaviors.tsx we expect form elements to have a name attributes
  // however a radio group is unique in that we want to manage a single value
  // for the entire group of radios. For a radio group, all the individual radio
  // elements have the same name, but there is no name attribute on the outer
  // wrapper as this attribute is not valid for this HTML element (typically a
  // div or a fieldset). In the special case of the radio group we make use of a
  // data-name attribute instead. The code in inputBehaviors.tsx looks for this
  // attribute when the name attribute does not exist.
  // Similarly, the front-end needs to be able to treat radios differently. To
  // support this we expose a data-type attribute so the front-end can correctly
  // detect the element type.
  // Finally, we also need to hoist the data-form-id attribute to the outer
  // attributes so that the front-end can ascertain which form state to update
  // when the radio group's value changes.
  $vars['attributes']['data-xb-name'] = $vars['element']['#name'];
  $vars['attributes']['data-xb-type'] = 'radios';
  // @todo Rename to xb-data-form-id in https://drupal.org/i//3517029.
  $vars['attributes']['data-form-id'] = $vars['element']['#attributes']['data-form-id'] ?? '';
}
