# Trigger CI.
experience_builder.component.*:
  type: config_entity
  constraints:
    FullyValidatable: ~
  mapping:
    label:
      type: required_label
      label: 'Label'
    # @see \Drupal\Core\Plugin\Component::$machineName
    component:
      type: machine_name
      label: 'Component'
      constraints:
        Regex:
          pattern: '/^[a-z0-9_-]+\+[a-z0-9_-]+$/'
          message: 'The %value machine name is not valid.'
    # All defaults for this Component made available through Experience Builder.
    defaults:
      type: mapping
      mapping:
        # Defaults for this SDC' props, keyed by SDC prop name, alphabetically.
        props:
          type: sequence
          orderby: key
          constraints: {}
          # Ensure a default is specified for EVERY prop of this component.
          # @todo Follow-up issue: implement this constraint, similar to the `CKEditor5EnabledConfigurablePlugins` constraint, with test coverage that causes existing config entities to fail if the props of an SDC change (because that is a BC break in the SDC).
          # KeyForEveryComponentProp: [%parent.component]
          sequence:
            type: mapping
            # For each SDC prop, first a field type must be picked from the list of possible choices provided by \Drupal\experience_builder\FieldForComponentSuggester
            # @todo MUCH later: field settings.
            mapping:
              field_type:
                type: string
                label: 'Default field type'
                # @todo Conditionally nullable: if truly zero field types can match this SDC prop shape.
                nullable: true
                constraints:
                  PluginExists:
                    manager: plugin.manager.field.field_type
                    interface: '\Drupal\Core\Field\FieldItemInterface'
                  Choice:
                    # @todo Currently, FieldForComponentSuggester assumes an entity context. We need to extract a new FieldTypeForComponentSuggester service out of that *first*. Until then, hardcode a list of possible field type choices.
                    - string
                    - uri
                    - file
                    - image
              # After a field type is selected, a field widget must be picked.
              # @todo MUCH later: widget settings.
              field_widget:
                type: string
                label: 'Default field widget'
                # @todo Add validation constraint because this is only *conditionally* nullable: if truly zero field types can match this SDC prop shape.
                nullable: true
                constraints:
                  PluginExists:
                    manager: plugin.manager.field.widget
                    interface: '\Drupal\Core\Field\WidgetInterface'
              # Then finally, a default value must be picked for every REQUIRED prop, using the aforementioned widget.
              # This value uses the field type's default value config schema, and will be simplified to a
              # StaticPropSource's `value`.
              # @see \Drupal\experience_builder\PropSource\StaticPropSource::denormalizeValue()
              # @see \Drupal\experience_builder\PropSource\StaticPropSource::isMinimalRepresentation()
              default_value:
                type: field.value.[%parent.field_type]
                label: 'Default value'
                # @todo Add validation constraint because this is only *conditionally* nullable: if the SDC prop is optional
                nullable: true
              # The default value must be retrievable
              expression:
                type: string
                label: ''
                # @todo Add validation constraint because this is only *conditionally* nullable: if truly zero field types can match this SDC prop shape.
                nullable: true
                constraints: {}
                # @todo Add `StructuredDataPropExpression` validation constraint that fails if StructuredDataPropExpression::fromString() fails
                # StructuredDataPropExpression: [field_type]

# The config equivalent of a ComponentTreeItem, validated by the same constraint.
# @todo Use this in https://www.drupal.org/project/experience_builder/issues/3455629
experience_builder.component_tree:
  type: mapping
  label: 'Config-Defined Component Tree'
  constraints:
    ValidComponentTree: ~
    FullyValidatable: ~
  # @see \Drupal\experience_builder\Plugin\Field\FieldType\ComponentTreeItem::propertyDefinitions()
  mapping:
    # @see \Drupal\experience_builder\Plugin\DataType\ComponentTreeStructure
    tree:
      type: label
      label: 'A component tree without props values.'
      constraints:
        ComponentTreeStructure: []
    # @see \Drupal\experience_builder\Plugin\DataType\ComponentPropsValues
    props:
      type: string
      label: 'Prop values for each component in the component tree'

field.value.component_tree:
  type: experience_builder.component_tree
  label: 'Default value'
  constraints:
    FullyValidatable: ~

field.field_settings.component_tree:
  type: field.field_settings.*
  constraints:
    FullyValidatable: ~
  mapping:
    translation:
      type: string
      label: 'Experience Builder translations'
      constraints:
        Choice:
          # @todo \Drupal\experience_builder\Plugin\Field\FieldType\ComponentTreeItem::defaultFieldSettings()
          - symmetric|asymmetric
