experience_builder.component.*:
  type: config_entity
  constraints:
    FullyValidatable: ~
  mapping:
    label:
      type: required_label
      label: 'Label'
    component:
      type: machine_name
      label: 'Component'
      constraints:
        Regex:
          pattern: '/^[a-z0-9_-]+\+[a-z0-9_-]+$/'
          message: 'The %value machine name is not valid.'

# @todo reuse the yet-to-be-written validation logic that \Drupal\experience_builder\Plugin\Field\FieldType\ComponentTreeItem::preSave() is referring to
field.value.component_tree:
  type: field.value.*
  label: 'Default value'
  # @see \Drupal\experience_builder\Plugin\Field\FieldType\ComponentTreeItem::propertyDefinitions()
  mapping:
    # @see \Drupal\experience_builder\Plugin\DataType\ComponentTreeStructure
    tree:
      type: label
      label: 'A component tree without props values.'
    # @see \Drupal\experience_builder\Plugin\DataType\ComponentPropsValues
    props:
      type: string
      label: 'Prop values for each component in the component tree'

field.field_settings.component_tree:
  type: field.field_settings.*
  constraints:
    FullyValidatable: ~
  mapping:
    translation:
      type: string
      label: 'Experience Builder translations'
      constraints:
        Choice:
          # @todo \Drupal\experience_builder\Plugin\Field\FieldType\ComponentTreeItem::defaultFieldSettings()
          - symmetric|asymmetric
