<?php

use Drupal\Core\Render\Markup;

/**
* Implements hook_library_info_alter().
*
* Remove the JS and CSS by setting it to an empty array. It is set to an empty array instead of unsetting
* the js and css keys because otherwise drupal throws an error about an incomplete
* library definition.
*/
function eb_vite_library_info_alter(&$libraries, $extension) {
    $libraries['eb-ui']['js'] = [];
    $libraries['eb-ui']['css'] = [];
}

/**
* Implements hook_preprocess_html().
* @see https://vitejs.dev/guide/backend-integration.html
*/
function eb_vite_preprocess_html(&$variables) {
  $vite_backend_integration_scripts = <<<HTML
    <script type="module">
      import RefreshRuntime from 'http://localhost:5173/@react-refresh'
      RefreshRuntime.injectIntoGlobalHook(window)
      window.\$RefreshReg\$ = () => {}
      window.\$RefreshSig\$ = () => (type) => type
      window.__vite_plugin_react_preamble_installed__ = true
    </script>
    <script type="module" src="http://localhost:5173/@vite/client"></script>
    <script type="module" src="http://localhost:5173/src/main.tsx"></script>
   HTML;

  $variables['page_bottom']['eb-ui']['#markup'] = Markup::create($vite_backend_integration_scripts);
}
