<?php

/**
* Implements hook_library_info_alter().
*/
function xb_vite_library_info_alter(&$libraries, $extension) {
  $base = [
    'attributes' => ['type' => 'module'],
    // Disabling preprocessing ensures these files are not aggregated, which
    // avoids the need for clearing Drupal caches during `npm run drupaldev`.
    'preprocess' => FALSE,
  ];

  // @see https://vitejs.dev/guide/backend-integration.html
  $libraries['xb-ui']['js'] = [
    'submodules/xb_vite/window.js' => $base,
    'http://localhost:5173/@vite/client' => ['type' => 'external'] + $base,
    'http://localhost:5173/src/main.tsx' => ['type' => 'external'] + $base,
  ];
  $libraries['xb-ui']['css'] = [];
}
