<?php

declare(strict_types=1);

use Drupal\experience_builder\PropExpressions\StructuredData\StructuredDataPropExpression;
use Drupal\experience_builder\PropShape\CandidateStorablePropShape;

/**
 * Implements hook_storage_prop_shape_alter().
 */
function xb_test_storage_prop_shape_alter_storage_prop_shape_alter(CandidateStorablePropShape $storable_prop_shape): void {
  if ($storable_prop_shape->shape->schema == ['type' => 'string', 'format' => 'uri']) {
    // @see \Drupal\Core\Field\Plugin\Field\FieldType\UriItem::propertyDefinitions()
    // @phpstan-ignore-next-line
    $storable_prop_shape->fieldTypeProp = StructuredDataPropExpression::fromString('ℹ︎uri␟value');
    // @see \Drupal\Core\Field\Plugin\Field\FieldType\UriItem::defaultFieldSettings()
    $storable_prop_shape->fieldInstanceSettings = NULL;
    // @see \Drupal\Core\Field\Plugin\Field\FieldWidget\UriWidget
    $storable_prop_shape->fieldWidget = 'uri';
  }
}

/**
 * Implements hook_field_widget_info_alter().
 */
function xb_test_storage_prop_shape_alter_field_widget_info_alter(array &$info): void {
  $info['uri']['xb'] = [
    'transforms' => [
      'mainProperty' => [],
    ],
  ];
}
