<?php

declare(strict_types=1);

namespace Drupal\Tests\canvas\Functional;

// cspell:ignore Bienvenue savoir Découvrez Identité visuelle

use Drupal\canvas\Entity\ContentTemplate;
use Drupal\canvas\Tmgmt\ComponentInputsConfigProcessor;
use Drupal\Core\Extension\ModuleInstallerInterface;
use Drupal\Tests\tmgmt\Functional\TmgmtTestTrait;
use Drupal\tmgmt\Entity\Job;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Group;

#[Group('canvas')]
#[Group('canvas_translation')]
#[CoversClass(ComponentInputsConfigProcessor::class)]
class ConfigWithComponentTreeTmgmtUiTest extends ConfigWithComponentTreeTranslationTestBase {

  use TmgmtTestTrait;

  public function test(): void {
    $module_installer = $this->container->get('module_installer');
    \assert($module_installer instanceof ModuleInstallerInterface);
    $module_installer->install(['tmgmt', 'tmgmt_config', 'tmgmt_test', 'canvas_dev_translation']);
    $this->rebuildContainer();

    $translator = $this->createTranslator([
      'name' => 'test_tmgmt',
      'label' => 'Test TMGMT',
      // @see \Drupal\tmgmt_test\Plugin\tmgmt\Translator\TestTranslator
      'plugin' => 'test_translator',
      'remote_languages_mappings' => [],
      'settings' => ['key' => 'test', 'another_key' => 'test'],
    ]);

    $job = $this->createJob('en', 'fr', $this->rootUser->id(), ['translator' => $translator->id()]);
    $job_item = $job->addItem('config', ContentTemplate::ENTITY_TYPE_ID, self::CONFIG_NAME);

    $job->setState(Job::STATE_ACTIVE);
    $translator->getPlugin()->requestTranslation($job);

    $this->drupalGet('admin/tmgmt/items/' . $job_item->id());
    $assert = $this->assertSession();
    $assert->statusCodeEquals(200);

    // Assert source texts visible for all edge cases.
    // Multiple-cardinality: each tag shown individually.
    $assert->pageTextContains('baz');
    $assert->pageTextContains('bar');
    $assert->pageTextContains('foo');
    // Plain prose.
    $assert->pageTextContains('Press');
    // URI-esque: requires `field.value.link` alteration.
    // @see \Drupal\canvas_dev_translation\Hook\ConfigTranslationSupportHooks::configSchemaInfoAlter()
    $assert->pageTextContains('https://www.drupal.org');
    // Banner plain prose.
    $assert->pageTextContains('A heading element! :)');
    // Rich prose: only value extracted, not format.
    $assert->pageTextContains('In a curious work, published in');

    // Assert translations generated by test_translator (prefix "fr: ").
    $assert->pageTextContains('fr: baz');
    $assert->pageTextContains('fr: bar');
    $assert->pageTextContains('fr: foo');
    $assert->pageTextContains('fr: Press');
    $assert->pageTextContains('fr: https://www.drupal.org');
    $assert->pageTextContains('fr: A heading element! :)');

    // SDC props populated by StaticPropSources are translatable.
    $assert->fieldExists('component_tree|' . self::UUID_MY_HERO . '|inputs|heading[translation]');
    $assert->fieldExists('component_tree|' . self::UUID_MY_HERO . '|inputs|cta2[translation]');
    // SDC prop populated by EntityFieldPropSource is NOT translatable.
    $assert->fieldNotExists('component_tree|' . self::UUID_MY_HERO . '|inputs|cta1[translation]');
    // SDC prop populated by HostEntityUrlPropSource is NOT translatable.
    $assert->fieldNotExists('component_tree|' . self::UUID_MY_HERO . '|inputs|cta1href[translation]');
    // Optional prop NOT populated in default is translatable: a translation may
    // opt to populate it even when the default translation leaves it empty.
    // @see \Drupal\canvas\Tmgmt\ComponentInputsConfigProcessor::extractTranslatablesIncludingEmpty()
    $assert->fieldExists('component_tree|' . self::UUID_MY_HERO . '|inputs|subheading[translation]');

    // Note: all other translatables get a `fr: ` prefix by the test translator.
    $this->submitForm([
      'component_tree|' . self::UUID_MY_HERO . '|inputs|subheading[translation]' => 'Découvrez Canvas',
      'component_tree|' . self::UUID_MY_HERO . '|inputs|heading[translation]' => 'Bienvenue à Canvas',
      'component_tree|' . self::UUID_MY_HERO . '|inputs|cta2[translation]' => 'En savoir plus',
      'component_tree|' . self::UUID_MY_CTA . '|inputs|href|uri[translation]' => 'https://fr.drupal.org',
      'component_tree|' . self::UUID_BRANDING . '|inputs|label[translation]' => 'Identité visuelle',
    ], 'Save as completed');
    $assert->pageTextContains('has been accepted');

    $this->assertTranslatedConfigComponentTree();
  }

}
