<?php

/**
 * @file
 * Post-update functions for the Canvas AI module.
 */

declare(strict_types=1);

use Drupal\Core\Config\FileStorage;

/**
 * Rebuild the router.
 *
 * Clears the route cache as this issue introduces changes to canvas_ai routes.
 *
 * @see https://www.drupal.org/project/canvas/issues/3533079
 */
function canvas_ai_post_update_0001_rebuild_router(): void {
  \Drupal::service('router.builder')->rebuild();
}

/**
 * Preserve the existing chat history limit for existing sites.
 */
function canvas_ai_post_update_0002_chat_history_max_messages(): void {
  $config = \Drupal::configFactory()->getEditable('canvas_ai.settings');

  // Existing sites effectively use a limit of 3, so keep that value here to
  // preserve current behavior. New installations get the newer default of
  // 10 from config/install/canvas_ai.settings.yml.
  if (!$config->isNew()) {
    $config->set('chat_history_max_messages', 3)->save(TRUE);
  }
}

/**
 * Reimport orchestrator agent as system prompt has changed.
 *
 * @see https://www.drupal.org/project/canvas/issues/3582390
 */
function canvas_ai_post_update_0003_reimport_orchestrator_agent(): void {
  $module_path = \Drupal::service('extension.list.module')->getPath('canvas_ai');
  $source = new FileStorage($module_path . '/config/install');
  $data = $source->read('ai_agents.ai_agent.canvas_ai_orchestrator');
  if ($data) {
    \Drupal::configFactory()
      ->getEditable('ai_agents.ai_agent.canvas_ai_orchestrator')
      ->setData($data)
      ->save(TRUE);

    $message = 'The Canvas AI orchestrator agent system prompt has been updated. If you had customized it directly, those changes have been overwritten. The recommended way to extend or alter agent behavior is through the Context Control Center or custom event subscribers.';
    \Drupal::logger('canvas_ai')->warning($message);
  }
}

/**
 * Enable hostname filter bypass for the Canvas Component Agent.
 *
 * Hostname filtering will interfere with the React code generated by
 * canvas_component_agent, so it must be disabled for the agent to work correctly.
 *
 * @see https://git.drupalcode.org/project/canvas/-/work_items/3590309
 */
function canvas_ai_post_update_0004_agent_hostname_filter(): void {
  $config = \Drupal::configFactory()
    ->getEditable('ai_agents.ai_agent.canvas_component_agent');
  if (!$config->isNew() && $config->get('hostname_filter_disabled') !== TRUE) {
    $config->set('hostname_filter_disabled', TRUE)->save(TRUE);
  }
}
