<?php

declare(strict_types=1);

use Drupal\node\Entity\NodeType;

/**
 * Implements hook_install().
 */
function canvas_dev_standard_install(): void {
  if (NodeType::load('article')) {
    \Drupal::service('entity_display.repository')
      ->getViewDisplay('node', 'article')
      ->setComponent('field_canvas_demo', [
        'label' => 'hidden',
        'type' => 'canvas_naive_render_sdc_tree',
        // The image field has weight -1 by default.
        'weight' => -2,
      ])
      ->save();
  }
}
