canvas_views.canvas_views_display.*:
  type: config_entity
  label: 'Canvas views display'
  constraints:
    FullyValidatable: ~
  mapping:
    id:
      type: machine_name
      label: 'ID'
    label:
      type: required_label
      label: 'Label'
    view_id:
      type: string
      label: 'View'
      constraints:
        NotBlank: ~
    component_tree:
      type: canvas.component_tree
      label: 'The designed display, rendered once per result row'
