<?php

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function xb_test_page_entity_base_field_info(EntityTypeInterface $entity_type): array {
  if ($entity_type->id() === 'xb_page') {
    $fields = [];
    $fields['xb_test_field'] = BaseFieldDefinition::create('string')
      ->setLabel(t('Test field'))
      ->setDescription(t('A test field'))
      ->setDisplayOptions('view', [
        'label' => 'above',
        'type' => 'string',
        'weight' => 0,
      ]);
    return $fields;
  }
  return [];
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function xb_test_page_xb_page_view(array &$build): void {
  $build['#attached']['drupalSettings']['xb_test_page'] = [
    'foo' => 'Bar',
  ];
  $build['#attached']['library'][] = 'core/drupalSettings';
  $build['xb_test_page_markup'] = [
    '#markup' => '<div id="xb-test-page-markup">xb_test_page_xb_page_view markup</div>',
  ];
}
